### ISSUE TITLE
Добавить установку зависимостей

### ISSUE THREAD

**Issue by VukW** [VukW/planning_markdown#1]
+зависимости (pip install requirements.txt)

**Comment by aleksartamonov** [comment]
Не уверен, что стоит это делать) По крайней мере надо дать пользователю выбрать. У меня, например pip стоит для 2го питона, а запускаю я командой python3 run.py

**Comment by VukW** [comment]
т.к. в докере теперь, то будем считать, что `pip install` допустим)
