### ISSUE TITLE
пустой markdown

### ISSUE THREAD

**Issue by VukW** [VukW/planning_markdown#7]
Сейчас если на картинке не было отмечено ни одного объекта, то в бд сохраняется заглушка: {point: [], region: [], segment: []}. А ты можешь плз сделать так, чтобы в такой ситуации не сохранялось вообще ничего (запрос даже не делался)? А то мне в бд хочется определять, какие картинки еще не имеют распознанную планировку, но не хочется завязываться на логику/структуру разметки

**Comment by ctrltz** [comment]
Да, это надо поправить)
